name: bear
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.5.0
  flutter_riverpod: ^2.6.1
  flex_color_picker: ^3.6.0
  logger: ^2.0.2
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true